export const READ_BOOKS_SUCCESSFUL = 'READ_BOOKS_SUCCESSFUL';
export const READ_BOOKS_PENDING = 'READ_BOOKS_PENDING';
export const READ_BOOKS_FAILURE = 'READ_BOOKS_FAILURE';

export const CREATE_BRANCH_REQUEST = 'CREATE_BRANCH_REQUEST';
export const CREATE_BRANCH_FAILURE = 'CREATE_BRANCH_FAILURE';
export const CREATE_BRANCH_SUCCESSFUL = 'CREATE_BRANCH_SUCCESSFUL';

export const READ_BRANCHES_SUCCESSFUL = 'READ_BRANCHES_SUCCESSFUL';
export const READ_BRANCHES_PENDING = 'READ_BRANCHES_PENDING';
export const READ_BRANCHES_FAILURE = 'READ_BRANCHES_FAILURE';

export const UPDATE_BRANCH_REQUEST = 'UPDATE_BRANCH_REQUEST';
export const UPDATE_BRANCH_FAILURE = 'UPDATE_BRANCH_FAILURE';
export const UPDATE_BRANCH_SUCCESSFUL = 'UPDATE_BRANCH_SUCCESSFUL';

export const DELETE_BRANCH_REQUEST = 'DELETE_BRANCH_REQUEST';
export const DELETE_BRANCH_FAILURE = 'DELETE_BRANCH_FAILURE';
export const DELETE_BRANCH_SUCCESSFUL = 'DELETE_BRANCH_SUCCESSFUL';

export const CREATE_PUBLISHER_REQUEST = 'CREATE_PUBLISHER_REQUEST';
export const CREATE_PUBLISHER_FAILURE = 'CREATE_PUBLISHER_FAILURE';
export const CREATE_PUBLISHER_SUCCESSFUL = 'CREATE_PUBLISHER_SUCCESSFUL';

export const READ_PUBLISHERS_SUCCESSFUL = 'READ_PUBLISHERS_SUCCESSFUL';
export const READ_PUBLISHERS_PENDING = 'READ_PUBLISHERS_PENDING';
export const READ_PUBLISHERS_FAILURE = 'READ_PUBLISHERS_FAILURE';

export const UPDATE_PUBLISHER_REQUEST = 'UPDATE_PUBLISHER_REQUEST';
export const UPDATE_PUBLISHER_FAILURE = 'UPDATE_PUBLISHER_FAILURE';
export const UPDATE_PUBLISHER_SUCCESSFUL = 'UPDATE_PUBLISHER_SUCCESSFUL';

export const DELETE_PUBLISHER_REQUEST = 'DELETE_PUBLISHER_REQUEST';
export const DELETE_PUBLISHER_FAILURE = 'DELETE_PUBLISHER_FAILURE';
export const DELETE_PUBLISHER_SUCCESSFUL = 'DELETE_PUBLISHER_SUCCESSFUL';
