export const CREATE_BOOK_REQUEST = 'CREATE_BOOK_REQUEST';
export const CREATE_BOOK_FAILURE = 'CREATE_BOOK_FAILURE';
export const CREATE_BOOK_SUCCESSFUL = 'CREATE_BOOK_SUCCESSFUL';
export const READ_BOOKS_SUCCESSFUL = 'READ_BOOKS_SUCCESSFUL';
export const READ_BOOKS_PENDING = 'READ_BOOKS_PENDING';
export const READ_BOOKS_FAILURE = 'READ_BOOKS_FAILURE';
export const UPDATE_BOOK_REQUEST = 'UPDATE_BOOK_REQUEST';
export const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE';
export const UPDATE_BOOK_SUCCESSFUL = 'UPDATE_BOOK_SUCCESSFUL';
export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST';
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
export const DELETE_BOOK_SUCCESSFUL = 'DELETE_BOOK_SUCCESSFUL';

export const CREATE_AUTHOR_REQUEST = 'CREATE_AUTHOR_REQUEST';
export const CREATE_AUTHOR_FAILURE = 'CREATE_AUTHOR_FAILURE';
export const CREATE_AUTHOR_SUCCESSFUL = 'CREATE_AUTHOR_SUCCESSFUL';
export const READ_AUTHORS_SUCCESSFUL = 'READ_AUTHORS_SUCCESSFUL';
export const READ_AUTHORS_PENDING = 'READ_AUTHORS_PENDING';
export const READ_AUTHORS_FAILURE = 'READ_AUTHORS_FAILURE';
export const UPDATE_AUTHOR_REQUEST = 'UPDATE_AUTHOR_REQUEST';
export const UPDATE_AUTHOR_FAILURE = 'UPDATE_AUTHOR_FAILURE';
export const UPDATE_AUTHOR_SUCCESSFUL = 'UPDATE_AUTHOR_SUCCESSFUL';
export const DELETE_AUTHOR_REQUEST = 'DELETE_AUTHOR_REQUEST';
export const DELETE_AUTHOR_FAILURE = 'DELETE_AUTHOR_FAILURE';
export const DELETE_AUTHOR_SUCCESSFUL = 'DELETE_AUTHOR_SUCCESSFUL';

export const CREATE_BRANCH_REQUEST = 'CREATE_BRANCH_REQUEST';
export const CREATE_BRANCH_FAILURE = 'CREATE_BRANCH_FAILURE';
export const CREATE_BRANCH_SUCCESSFUL = 'CREATE_BRANCH_SUCCESSFUL';
export const READ_BRANCHES_SUCCESSFUL = 'READ_BRANCHES_SUCCESSFUL';
export const READ_BRANCHES_PENDING = 'READ_BRANCHES_PENDING';
export const READ_BRANCHES_FAILURE = 'READ_BRANCHES_FAILURE';
export const UPDATE_BRANCH_REQUEST = 'UPDATE_BRANCH_REQUEST';
export const UPDATE_BRANCH_FAILURE = 'UPDATE_BRANCH_FAILURE';
export const UPDATE_BRANCH_SUCCESSFUL = 'UPDATE_BRANCH_SUCCESSFUL';
export const DELETE_BRANCH_REQUEST = 'DELETE_BRANCH_REQUEST';
export const DELETE_BRANCH_FAILURE = 'DELETE_BRANCH_FAILURE';
export const DELETE_BRANCH_SUCCESSFUL = 'DELETE_BRANCH_SUCCESSFUL';

export const CREATE_BORROWER_REQUEST = 'CREATE_BORROWER_REQUEST';
export const CREATE_BORROWER_FAILURE = 'CREATE_BORROWER_FAILURE';
export const CREATE_BORROWER_SUCCESSFUL = 'CREATE_BORROWER_SUCCESSFUL';
export const READ_BORROWERS_SUCCESSFUL = 'READ_BORROWERS_SUCCESSFUL';
export const READ_BORROWERS_PENDING = 'READ_BORROWERS_PENDING';
export const READ_BORROWERS_FAILURE = 'READ_BORROWERS_FAILURE';
export const UPDATE_BORROWER_REQUEST = 'UPDATE_BORROWER_REQUEST';
export const UPDATE_BORROWER_FAILURE = 'UPDATE_BORROWER_FAILURE';
export const UPDATE_BORROWER_SUCCESSFUL = 'UPDATE_BORROWER_SUCCESSFUL';
export const DELETE_BORROWER_REQUEST = 'DELETE_BORROWER_REQUEST';
export const DELETE_BORROWER_FAILURE = 'DELETE_BORROWER_FAILURE';
export const DELETE_BORROWER_SUCCESSFUL = 'DELETE_BORROWER_SUCCESSFUL';

export const CREATE_COPIES_REQUEST = 'CREATE_COPIES_REQUEST';
export const CREATE_COPIES_FAILURE = 'CREATE_COPIES_FAILURE';
export const CREATE_COPIES_SUCCESSFUL = 'CREATE_COPIES_SUCCESSFUL';
export const CREATE_NON_COPIES_REQUEST = 'CREATE_NON_COPIES_REQUEST';
export const CREATE_NON_COPIES_FAILURE = 'CREATE_NON_COPIES_FAILURE';
export const CREATE_NON_COPIES_SUCCESSFUL = 'CREATE_NON_COPIES_SUCCESSFUL';

export const BRANCH_SELECT = 'BRANCH_SELECT';

export const READ_COPIES_SUCCESSFUL = 'READ_COPIES_SUCCESSFUL';
export const READ_COPIES_PENDING = 'READ_COPIES_PENDING';
export const READ_COPIES_FAILURE = 'READ_COPIES_FAILURE';

export const READ_NON_COPIES_SUCCESSFUL = 'READ_NON_COPIES_SUCCESSFUL';
export const READ_NON_COPIES_PENDING = 'READ_NON_COPIES_PENDING';
export const READ_NON_COPIES_FAILURE = 'READ_NON_COPIES_FAILURE';

export const LIBRARIAN_START_READ_BRANCH_BOOKS = 'LIBRARIAN_START_READ_BRANCH_BOOKS';
export const LIBRARIAN_START_READ_NON_BRANCH_BOOKS =
	'LIBRARIAN_START_READ_NON_BRANCH_BOOKS';
export const LIBRARIAN_READ_ALL_BRANCHES_FAILED = 'LIBRARIAN_READ_ALL_BRANCHES_FAILED';
export const LIBRARIAN_READ_ALL_BRANCHES_SUCCESSFUL =
	'LIBRARIAN_READ_ALL_BRANCHES_SUCCESSFUL';
export const LIBRARIAN_DASHBOARD_SELECT_BRANCH = 'LIBRARIAN_DASHBOARD_SELECT_BRANCH';
export const LIBRARIAN_DASHBOARD_READ_BOOKS_FAILED =
	'LIBRARIAN_DASHBOARD_READ_BOOKS_FAILED';
export const LIBRARIAN_DASHBOARD_READ_BOOKS_SUCCESSFUL =
	'LIBRARIAN_DASHBOARD_READ_BOOKS_SUCCESSFUL';
export const LIBRARIAN_READ_BRANCH_BOOKS_PENDING = 'LIBRARIAN_READ_BRANCH_BOOKS_PENDING';
export const LIBRARIAN_READ_BRANCH_BOOKS_FAILURE = 'LIBRARIAN_READ_BRANCH_BOOKS_FAILURE';
export const LIBRARIAN_READ_BRANCH_BOOKS_SUCCESSFUL =
	'LIBRARIAN_READ_BRANCH_BOOKS_SUCCESSFUL';
export const LIBRARIAN_SELECT_BRANCH = 'LIBRARIAN_SELECT_BRANCH';
export const LIBRARIAN_SWITCH = 'LIBRARIAN_SWITCH';

export const CREATE_GENRE_REQUEST = 'CREATE_GENRE_REQUEST';
export const CREATE_GENRE_EXISTS = 'CREATE_GENRE_EXISTS';
export const CREATE_GENRE_FAILURE = 'CREATE_GENRE_FAILURE';
export const CREATE_GENRE_SUCCESSFUL = 'CREATE_GENRE_SUCCESSFUL';
export const READ_GENRES_SUCCESSFUL = 'READ_GENRES_SUCCESSFUL';
export const READ_GENRES_PENDING = 'READ_GENRES_PENDING';
export const READ_GENRES_FAILURE = 'READ_GENRES_FAILURE';
export const UPDATE_GENRE_REQUEST = 'UPDATE_GENRE_REQUEST';
export const UPDATE_GENRE_EXISTS = 'UPDATE_GENRE_EXISTS';
export const UPDATE_GENRE_FAILURE = 'UPDATE_GENRE_FAILURE';
export const UPDATE_GENRE_SUCCESSFUL = 'UPDATE_GENRE_SUCCESSFUL';
export const DELETE_GENRE_REQUEST = 'DELETE_GENRE_REQUEST';
export const DELETE_GENRE_FAILURE = 'DELETE_GENRE_FAILURE';
export const DELETE_GENRE_SUCCESSFUL = 'DELETE_GENRE_SUCCESSFUL';

export const READ_LOANS_SUCCESSFUL = 'READ_LOANS_SUCCESSFUL';
export const READ_LOANS_PENDING = 'READ_LOANS_PENDING';
export const READ_LOANS_FAILURE = 'READ_LOANS_FAILURE';
export const EXTEND_LOAN_REQUEST = 'EXTEND_LOAN_REQUEST';
export const EXTEND_LOAN_FAILURE = 'EXTEND_LOAN_FAILURE';
export const EXTEND_LOAN_SUCCESSFUL = 'EXTEND_LOAN_SUCCESSFUL';

export const CREATE_PUBLISHER_REQUEST = 'CREATE_PUBLISHER_REQUEST';
export const CREATE_PUBLISHER_FAILURE = 'CREATE_PUBLISHER_FAILURE';
export const CREATE_PUBLISHER_SUCCESSFUL = 'CREATE_PUBLISHER_SUCCESSFUL';
export const READ_PUBLISHERS_SUCCESSFUL = 'READ_PUBLISHERS_SUCCESSFUL';
export const READ_PUBLISHERS_PENDING = 'READ_PUBLISHERS_PENDING';
export const READ_PUBLISHERS_FAILURE = 'READ_PUBLISHERS_FAILURE';
export const UPDATE_PUBLISHER_REQUEST = 'UPDATE_PUBLISHER_REQUEST';
export const UPDATE_PUBLISHER_FAILURE = 'UPDATE_PUBLISHER_FAILURE';
export const UPDATE_PUBLISHER_SUCCESSFUL = 'UPDATE_PUBLISHER_SUCCESSFUL';
export const DELETE_PUBLISHER_REQUEST = 'DELETE_PUBLISHER_REQUEST';
export const DELETE_PUBLISHER_FAILURE = 'DELETE_PUBLISHER_FAILURE';
export const DELETE_PUBLISHER_SUCCESSFUL = 'DELETE_PUBLISHER_SUCCESSFUL';

export const BORROWER_BACK_TO_BRANCH_SELECT = 'BORROWER_BACK_TO_BRANCH_SELECT';
export const BORROWER_LOGIN_PENDING = 'BORROWER_LOGIN_PENDING';
export const BORROWER_LOGIN_FAILURE = 'BORROWER_LOGIN_FAILURE';
export const BORROWER_LOGIN_SUCCESSFUL = 'BORROWER_LOGIN_SUCCESSFUL';
export const BORROWER_LOGOUT = 'BORROWER_LOGOUT';
export const BORROWER_START_CHECKOUT = 'BORROWER_START_CHECKOUT';
export const BORROWER_START_RETURN = 'BORROWER_START_RETURN';
export const BORROWER_READ_ALL_BRANCHES_FAILED = 'BORROWER_READ_ALL_BRANCHES_FAILED';
export const BORROWER_READ_ALL_BRANCHES_SUCCESSFUL =
	'BORROWER_READ_ALL_BRANCHES_SUCCESSFUL';
export const BORROWER_DASHBOARD_SELECT_BRANCH = 'BORROWER_DASHBOARD_SELECT_BRANCH';
export const BORROWER_DASHBOARD_READ_BOOKS_FAILED =
	'BORROWER_DASHBOARD_READ_BOOKS_FAILED';
export const BORROWER_DASHBOARD_READ_BOOKS_SUCCESSFUL =
	'BORROWER_DASHBOARD_READ_BOOKS_SUCCESSFUL';
export const BORROWER_CHECKOUT_PENDING = 'BORROWER_CHECKOUT_PENDING';
export const BORROWER_CHECKOUT_FAILURE = 'BORROWER_CHECKOUT_FAILURE';
export const BORROWER_CHECKOUT_SUCCESSFUL = 'BORROWER_CHECKOUT_SUCCESSFUL';
export const BORROWER_CLOSE_CHECKOUT_MODAL = 'BORROWER_CLOSE_CHECKOUT_MODAL';
export const BORROWER_READ_ACTIVE_LOANS_SUCCESSFUL =
	'BORROWER_READ_ACTIVE_LOANS_SUCCESSFUL';
export const BORROWER_READ_ACTIVE_LOANS_FAILED = 'BORROWER_READ_ACTIVE_LOANS_FAILED';
export const BORROWER_RETURN_PENDING = 'BORROWER_RETURN_PENDING';
export const BORROWER_RETURN_FAILURE = 'BORROWER_RETURN_FAILURE';
export const BORROWER_RETURN_SUCCESSFUL = 'BORROWER_RETURN_SUCCESSFUL';
export const BORROWER_CLOSE_RETURN_MODAL = 'BORROWER_CLOSE_RETURN_MODAL';
